name: Build Python Application

on:
  push:
    branches: main
  pull_request:
    branches: main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install auto-py-to-exe

      - name: Create build
        run: pyinstaller --noconfirm --onefile --name "backend-python.bin" "backend-python.py"

      - name: Create version
        id: create_version
        shell: python
        run: |
          from datetime import datetime
          from os import getenv

          DATE_Y = int(datetime.now().strftime(format="%y"))
          DATE_M = int(datetime.now().strftime(format="%m"))
          DATE_D = int(datetime.now().strftime(format="%d"))
          TIME = str(int(datetime.now().strftime(format="%H%M%S"))).rjust(6, "0")

          VERSION = f"v{DATE_Y}.{DATE_M}.{DATE_D}.{TIME}"

          print(VERSION)

          with open(file=getenv(key="GITHUB_OUTPUT"),
                    mode="a") as github_output_file:
              github_output_file.write(f"version={VERSION}")

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: "backend-python"
          tag_name: ${{ steps.create_version.outputs.version }}
          body: ${{ steps.create_version.outputs.version }}
          files: ./dist/backend-python.bin
          fail_on_unmatched_files: true
